### ISSUE TITLE
node index 之后就报错了

### ISSUE THREAD

**Issue by addstone** [ljc0910/dianzan-web#1]
(node:16448) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:16448) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:16448) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
run at 4006
(node:16448) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (D:\github\dianzan-web\node_modules\mongodb\lib\core\topologies\server.js:431:11)
    at Pool.emit (events.js:210:5)
    at D:\github\dianzan-web\node_modules\mongodb\lib\core\connection\pool.js:580:14
    at D:\github\dianzan-web\node_modules\mongodb\lib\core\connection\connect.js:39:11
    at callback (D:\github\dianzan-web\node_modules\mongodb\lib\core\connection\connect.js:261:5)
    at Socket.<anonymous> (D:\github\dianzan-web\node_modules\mongodb\lib\core\connection\connect.js:286:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:16448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

软件版本：
win 10 企业版 1903 vccode 1.38   node 12.11.0

**Comment by ljc0910** [comment]
这个版本需要链接数据库的。如果你只是想看一下点赞的效果，建议拉取   https://github.com/ljc0910/qq-area-dianzan
